### ISSUE TITLE
GetAccessToken() Issue on IOS

### ISSUE THREAD

**Issue by davohambardzumyan** [brim-borium/spotify_sdk#229]
I am trying to get access token:

```
String accessToken = await SpotifySdk.getAccessToken(
    clientId: clientId,    redirectUrl: redirectUrl,
    scope: 'app-remote-control, user-modify-playback-state');
```
    
 **But get error** 
    
  ```
  [+5767 ms] flutter: \^[[38;5;196m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
[        ] flutter: \^[[38;5;196m│ #0   SpotifySdk._logException (package:spotify_sdk/spotify_sdk.dart:653:15)<…>
[        ] flutter: \^[[38;5;196m│ #1   SpotifySdk.getAccessToken (package:spotify_sdk/spotify_sdk.dart:131:7)<…>
[        ] flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
[        ] flutter: \^[[38;5;196m│ ⛔ getAccessToken failed with: <…>
[        ] flutter: \^[[38;5;196m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
[        ] flutter: spotify error PlatformException(authenticationTokenError, null, null, null)
```

**Comment by Mohamed-Abdulla** [comment]
could u able to fix it?

**Comment by Jonny5-5** [comment]
I am also experiencing this issue. @davohambardzumyan Did you ever find a solution?

**Comment by socsob** [comment]
Could be a couple of things based on the limited info:
- Within the Spotify dev dashboard did you go under user management and add the account email address? This is necessary before requesting a quota extension. 
- Did you set up the appropriate redirect uri back into your app in the Spotify dev dashboard?
- Within your Spotify dev dashboard did you put the appropriate ios Bundle Id/android package matching your project?

**Comment by Jonny5-5** [comment]
In my case, everything works fine on iOS when I use the same parameters with a different auth package and it works as intended. So I want to rule out Spotify my setup as the issue. I used the example project and modified the necessary callbacks and id/secret and had the same issue.

**Comment by socsob** [comment]
> In my case, everything works fine on iOS when I use the same parameters with a different auth package and it works as intended. So I want to rule out Spotify my setup as the issue. I used the example project and modified the necessary callbacks and id/secret and had the same issue.

Currently using the latest version on pub.dev and it works fully on my iPhone 14 physical device

**Comment by evanagovino** [comment]
Super frustrating that the the PlatformException doesn't return any detail. Was banging my head against the wall for the last few hours until I realized that the iOS app _requires_ the app-remote-control scope which I wasn't previously using for my app. If you haven't tried, it may be worth it to try with a new app (so new clientID) in development mode that allows all scopes. Definitely follow up here and let us know if you're still having issues!

**Comment by daniel-toporovsky** [comment]
Same issue:

flutter:  3.27.4
spotify_sdk: ^3.0.2
iOS: 18.4.1 


`
CLIENT OF UIKIT REQUIRES UPDATE: This process does not adopt UIScene lifecycle. This will become an assert in a future version.
flutter: The Dart VM service is listening on http://127.0.0.1:55109/5pfUn97HAQI=/
Snapshot request 0x121814f90 complete with error: <NSError: 0x121815d10; domain: BSActionErrorDomain; code: 6 ("anulled")>
flutter: \^[[38;5;196m┌───────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;196m│ #0   SpotifySdk._logException (package:spotify_sdk/spotify_sdk.dart:653:15)<…>
flutter: \^[[38;5;196m│ #1   SpotifySdk.connectToSpotifyRemote (package:spotify_sdk/spotify_sdk.dart:94:7)<…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ ⛔ connectToSpotify failed with: An unknown error has occured<…>
flutter: \^[[38;5;196m└───────────────────────────────────────────────────────────────────────────<…>
`

**Comment by richanshah** [comment]
@evanagovino can u let me know what changes you have done?

**Comment by brim-borium** [comment]
Resolved in `v4.0.0` (see #257) with updated native iOS SDK bindings and error propagation.
